id: IE2E1665E
legacy_id: P006874
ocr_import_info:
  bdrc_scan_id: W3CN4729
  source: bdrc
  ocr_info:
    timestamp: '2020-03-27T06:33:30'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-03T14:36:01.471505+00:00'
last_modified: 2022-09-03 22:36:19.909553
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W3CN4729
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW3CN4729
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: རྣམ་དག་བདེ་ཆེན་ཞིང་གི་སྨོན་ལམ་གྱི་འགྲེལ་བཤད་ཐར་ལམ་སྣང་བྱེད།
  author: གནས་མདོ་ཀརྨ་ཆགས་མེད།
statistics:
  ocr_word_mean_confidence_index: 0.7013482846263429
  ocr_word_median_confidence_index: 0.9599999785423279
quality: null
bases:
  I3CN4731:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN4731
      total_pages: 456
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I3CN4731.txt
    statistics:
      ocr_word_median_confidence_index: 0.9599999785423279
      ocr_word_mean_confidence_index: 0.7013482846263429
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
